FROM php:apache             //specifies where to run from
RUN apt-get install -y        //generaL UPDATE command
RUN docker-php-exe-install    // run required installations
COPY . /var/www/html          // copy everything to specified path 
